/**:
  ros__parameters:
    min_longitudinal_offset: 2.1
    max_longitudinal_offset: 2.15
    min_lateral_offset: -0.6125
    max_lateral_offset: 0.7425
    min_height_offset: 0.9
    max_height_offset: 1.0
